### ISSUE TITLE
дока да

### ISSUE THREAD

**Issue by alexeyzer** [alexeyzer/SerialPortApp#4]
Доку сделать да чтобы красиво было читалось легко как на пароме в кейптауне да всего хорошего

**Comment by perlinleo** [comment]
надо бы доку сделать конечно

**Comment by andrew-kireev** [comment]
Надо бы надо бы, только ктож ее сделает...

**Comment by alexeyzer** [comment]
Так Киреев у нас на аутсорсе и сделает

**Comment by andrew-kireev** [comment]
Это хто такой?

**Comment by alexeyzer** [comment]
Да дикий один ходит суету наводит доку за час 10 минут делает, а потом авито поднимает на своём ноуте, псих...

**Comment by perlinleo** [comment]
1. Сделать доку 
2. Сделать доку

- [ ] д

- [ ] о

- [ ] к

- [ ] у

- [ ] м
е
- [ ]н 

- [ ] т
а
- [ ] ция
