### ISSUE TITLE
Сделать

### ISSUE THREAD

**Issue by perlinleo** [alexeyzer/SerialPortApp#7]
- [x] Допилить уведомления об открытии файла, когда нажимается кнопка будет посылаться на родительский ( на тот компьютер с которого отправлен файл ) будет отправляться сообщение что файл открыт

- [x] Хуйня с пафами (файл должен сохраняться в выбранном пути ,а не там где лежит программа))))

- [x] Теперь в регистрации будет летать не просто пакет а пакет с именами 

Таблица пользователей
|  ID  |  Имя           | 
| ------------- |:-------------:|
| 1    | Леонид Перлин | 
| 2      | Андрей Киреев |  
| 3  |  Алексей Зудин  |

**Comment by alexeyzer** [comment]
Сделал штуку с пафами и увеличил скорость перессылки файлов

**Comment by alexeyzer** [comment]
уведомления об открытии файла теперь улетают на компьютер который этот файл прислал
